<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit46e255a2d5df821a01e176b3ff93463a
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Tholu\\Packer\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Tholu\\Packer\\' => 
        array (
            0 => __DIR__ . '/..' . '/tholu/php-packer/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit46e255a2d5df821a01e176b3ff93463a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit46e255a2d5df821a01e176b3ff93463a::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
